# Generated by Django 3.2 on 2022-01-18 13:46

import bareme.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bareme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'baremes',
            },
        ),
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=bareme.models.getCode, max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('type_calcule', models.CharField(choices=[('Calcule par unité TC', 'Calcule par unité TC'), ('Calcule par unité JOUR', 'Calcule par unité JOUR'), ('Calcule par unité TC X JOUR', 'Calcule par unité TC X JOUR'), ('Calcule par unité ARTICLE', 'Calcule par unité ARTICLE'), ('A la demande', 'A la demande')], max_length=30)),
                ('categorie', models.CharField(blank=True, choices=[('Automatique', 'Automatique'), ('Clarck Intégral', 'Clarck Intégral'), ('Clarck Partiel', 'Clarck Partiel'), ('Dangereux', 'Dangereux'), ('Dépotage', 'Dépotage'), ('Manutentions humaines Intégral', 'Manutentions humaines Intégral'), ('Manutentions humaines Partiel', 'Manutentions humaines Partiel'), ('Préstation occasionnelle', 'Préstation occasionnelle'), ('Scanner', 'Scanner'), ('Visite', 'Visite')], max_length=30, null=True)),
                ('code_comptable', models.IntegerField(default=0)),
                ('appliquer_pour', models.CharField(choices=[('Client', 'Client'), ('Groupeur', 'Groupeur'), ('Client et Groupeur', 'Client et Groupeur')], default='Client', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'rebriques',
            },
        ),
        migrations.CreateModel(
            name='Sejour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dangereux', models.BooleanField(default=False)),
                ('frigo', models.BooleanField(default=False)),
                ('jour_min', models.IntegerField(blank=True)),
                ('jour_max', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('bareme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bareme.bareme')),
                ('type_tc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.type')),
            ],
            options={
                'verbose_name_plural': 'séjours',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PrestationOccasionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubrique', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tc')),
            ],
            options={
                'verbose_name_plural': 'prestations occasionnelle',
            },
        ),
        migrations.CreateModel(
            name='PrestationArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('bareme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bareme.bareme')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bareme.rubrique')),
            ],
            options={
                'verbose_name_plural': 'prestations article',
            },
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dangereux', models.BooleanField(default=False, null=True)),
                ('frigo', models.BooleanField(default=False, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('bareme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bareme.bareme')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bareme.rubrique')),
                ('type_tc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.type')),
            ],
            options={
                'verbose_name_plural': 'prestations',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSejour',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('dangereux', models.BooleanField(default=False)),
                ('frigo', models.BooleanField(default=False)),
                ('jour_min', models.IntegerField(blank=True)),
                ('jour_max', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bareme', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bareme.bareme')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type_tc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reference.type')),
            ],
            options={
                'verbose_name': 'historical sejour',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRubrique',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(default=bareme.models.getCode, max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('type_calcule', models.CharField(choices=[('Calcule par unité TC', 'Calcule par unité TC'), ('Calcule par unité JOUR', 'Calcule par unité JOUR'), ('Calcule par unité TC X JOUR', 'Calcule par unité TC X JOUR'), ('Calcule par unité ARTICLE', 'Calcule par unité ARTICLE'), ('A la demande', 'A la demande')], max_length=30)),
                ('categorie', models.CharField(blank=True, choices=[('Automatique', 'Automatique'), ('Clarck Intégral', 'Clarck Intégral'), ('Clarck Partiel', 'Clarck Partiel'), ('Dangereux', 'Dangereux'), ('Dépotage', 'Dépotage'), ('Manutentions humaines Intégral', 'Manutentions humaines Intégral'), ('Manutentions humaines Partiel', 'Manutentions humaines Partiel'), ('Préstation occasionnelle', 'Préstation occasionnelle'), ('Scanner', 'Scanner'), ('Visite', 'Visite')], max_length=30, null=True)),
                ('code_comptable', models.IntegerField(default=0)),
                ('appliquer_pour', models.CharField(choices=[('Client', 'Client'), ('Groupeur', 'Groupeur'), ('Client et Groupeur', 'Client et Groupeur')], default='Client', max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical rubrique',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPrestationOccasionnelle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rubrique', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.tc')),
            ],
            options={
                'verbose_name': 'historical prestation occasionnelle',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPrestationArticle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bareme', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bareme.bareme')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rubrique', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bareme.rubrique')),
            ],
            options={
                'verbose_name': 'historical prestation article',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPrestation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('dangereux', models.BooleanField(default=False, null=True)),
                ('frigo', models.BooleanField(default=False, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bareme', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bareme.bareme')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rubrique', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bareme.rubrique')),
                ('type_tc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reference.type')),
            ],
            options={
                'verbose_name': 'historical prestation',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBranchement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('jour_min', models.IntegerField(blank=True)),
                ('jour_max', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bareme', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bareme.bareme')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type_tc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reference.type')),
            ],
            options={
                'verbose_name': 'historical branchement',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBareme',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bareme',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Branchement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_min', models.IntegerField(blank=True)),
                ('jour_max', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('bareme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bareme.bareme')),
                ('type_tc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.type')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
