# Generated by Django 3.2 on 2022-02-02 13:58

import bareme.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bareme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default=bareme.models.getCode, max_length=50)),
                ('methode_calcule', models.CharField(choices=[("A la date d'accostage", "A la date d'accostage"), ("A l'entéée du premier TC", "A l'entéée du premier TC"), ("A l'entrée du dernier TC", "A l'entrée du dernier TC")], default=2, max_length=50)),
                ('bareme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bareme.bareme')),
            ],
        ),
    ]
