# Generated by Django 3.2 on 2022-02-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bareme', '0003_regime_enterposage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regime',
            name='designation',
            field=models.CharField(max_length=50),
        ),
    ]
