# Generated by Django 3.2 on 2022-02-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bareme', '0004_alter_regime_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='regime',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
