# Generated by Django 3.2 on 2022-02-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bareme', '0006_alter_regime_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regime',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
