# Generated by Django 4.0.3 on 2022-04-11 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bareme', '0011_alter_historicalrubrique_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SejourGroupage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dangereux', models.BooleanField(default=False)),
                ('jour_min', models.IntegerField(blank=True)),
                ('jour_max', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('bareme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bareme.bareme')),
            ],
            options={
                'verbose_name_plural': 'séjours',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PrestationGroupage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dangereux', models.BooleanField(blank=True, default=False, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('bareme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bareme.bareme', verbose_name='Bareme groupage')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bareme.rubrique')),
            ],
            options={
                'verbose_name_plural': 'prestations',
                'ordering': ['id'],
            },
        ),
    ]
