# Generated by Django 4.0.3 on 2022-04-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bareme', '0012_sejourgroupage_prestationgroupage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestationgroupage',
            options={'ordering': ['id'], 'verbose_name_plural': 'prestations groupage'},
        ),
        migrations.AlterModelOptions(
            name='sejourgroupage',
            options={'ordering': ['id'], 'verbose_name_plural': 'séjours groupage'},
        ),
    ]
