# Generated by Django 4.0.3 on 2022-04-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bareme', '0013_alter_prestationgroupage_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SejourGroupage',
            new_name='PrestationVisiteGroupage',
        ),
    ]
