# Generated by Django 4.0.3 on 2022-04-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bareme', '0014_rename_sejourgroupage_prestationvisitegroupage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestationvisitegroupage',
            options={'ordering': ['id'], 'verbose_name_plural': 'prestations visite groupage'},
        ),
        migrations.RenameField(
            model_name='prestationvisitegroupage',
            old_name='jour_max',
            new_name='volume_max',
        ),
        migrations.RenameField(
            model_name='prestationvisitegroupage',
            old_name='jour_min',
            new_name='volume_min',
        ),
    ]
