# Generated by Django 3.2.16 on 2022-10-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bareme', '0017_alter_historicalrubrique_categorie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalbareme',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical bareme', 'verbose_name_plural': 'historical baremes'},
        ),
        migrations.AlterModelOptions(
            name='historicalbranchement',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical branchement', 'verbose_name_plural': 'historical branchements'},
        ),
        migrations.AlterModelOptions(
            name='historicalprestation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical prestation', 'verbose_name_plural': 'historical prestations'},
        ),
        migrations.AlterModelOptions(
            name='historicalprestationarticle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical prestation article', 'verbose_name_plural': 'historical prestations article'},
        ),
        migrations.AlterModelOptions(
            name='historicalprestationoccasionnelle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical prestation occasionnelle', 'verbose_name_plural': 'historical prestations occasionnelle'},
        ),
        migrations.AlterModelOptions(
            name='historicalrubrique',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical rubrique', 'verbose_name_plural': 'historical rebriques'},
        ),
        migrations.AlterModelOptions(
            name='historicalsejour',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical sejour', 'verbose_name_plural': 'historical séjours'},
        ),
        migrations.AlterField(
            model_name='historicalbareme',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalbranchement',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalprestation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalprestationarticle',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalprestationoccasionnelle',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalrubrique',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsejour',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
