# Generated by Django 3.2.16 on 2022-10-23 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0003_box_parc'),
        ('bareme', '0018_auto_20221005_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprestation',
            name='groupage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='prestation',
            name='groupage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='SejourTcGroupage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dangereux', models.BooleanField(default=False)),
                ('frigo', models.BooleanField(default=False)),
                ('jour_min', models.IntegerField(blank=True)),
                ('jour_max', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('bareme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bareme.bareme')),
                ('type_tc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.type')),
            ],
            options={
                'verbose_name_plural': 'séjours',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSejourTcGroupage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('dangereux', models.BooleanField(default=False)),
                ('frigo', models.BooleanField(default=False)),
                ('jour_min', models.IntegerField(blank=True)),
                ('jour_max', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bareme', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bareme.bareme')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type_tc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reference.type')),
            ],
            options={
                'verbose_name': 'historical sejour tc groupage',
                'verbose_name_plural': 'historical séjours',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
