# Generated by Django 3.2.16 on 2022-10-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bareme', '0019_auto_20221023_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsejourtcgroupage',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical sejour tc groupage', 'verbose_name_plural': 'historical séjours groupage'},
        ),
        migrations.AlterModelOptions(
            name='sejourtcgroupage',
            options={'ordering': ['id'], 'verbose_name_plural': 'séjours groupage'},
        ),
        migrations.AddField(
            model_name='historicalprestationarticle',
            name='groupage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='prestationarticle',
            name='groupage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
