# Generated by Django 4.1.5 on 2023-02-06 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0025_sousarticle_bl'),
        ('bareme', '0020_auto_20221023_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestationOccasionnelleGroupage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubrique', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('sous_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sousarticle')),
            ],
            options={
                'verbose_name_plural': 'prestations occasionnelle groupage',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrestationOccasionnelleGroupage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rubrique', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sous_article', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.sousarticle')),
            ],
            options={
                'verbose_name': 'historical prestation occasionnelle groupage',
                'verbose_name_plural': 'historical prestations occasionnelle groupage',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
