# Generated by Django 4.2.5 on 2023-10-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_direction'),
        ('bareme', '0024_bareme_accostage_historicalbareme_accostage'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrubrique',
            name='direction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reference.direction'),
        ),
        migrations.AddField(
            model_name='rubrique',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.direction'),
        ),
        migrations.AlterField(
            model_name='historicalrubrique',
            name='code_comptable',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rubrique',
            name='code_comptable',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
