# Generated by Django 4.2.5 on 2023-10-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bareme', '0025_historicalrubrique_direction_rubrique_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprestationoccasionnelle',
            name='prix',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='prestationoccasionnelle',
            name='prix',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
