import type { ColumnsType } from "antd/es/table";
import { Tag } from "antd";


function getColor(entry:any) {

  const number = parseInt(entry, 10);

  switch (number) {
      case 1:
          return 'green';
      case 2:
          return 'orange';
      case 3:
          return 'yellow';
      case 4:
          return 'red';
      case 5:
          return 'blue';
      case 6:
          return 'indigo';
      case 7:
          return 'violet';
      case 8:
          return 'brown';
      case 9:
          return 'pink';
      case 10:
          return 'gray';
      default:
        return 'indigo';
  }
}


export const BREADCRUMBS: any = [
    { text: "Acciel", link: true, to: "/" },
    { text: "References", link: false, to: "" },
    { text: "Gros", link: false, to: "" },
]


export const GROS_COLUMNS = [
  {
    title:"Numero",
    dataIndex:"gros",
    schema:['gros', 'numero'],
    render: (record:any) => record?.numero,
    key:"gros_numero",
    expand:"gros.numero",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Gros",
    dataIndex:"gros",
    schema:['gros', 'gros'],
    render: (record:any) => record?.gros,
    key:"gros_gros",
    expand:"gros.gros",
    checked:true,
    width:150,
    ellipsis: true,
},
{
    title:"Escale",
    dataIndex:"gros",
    schema:['gros', 'escale'],
    render: (record:any) => record?.escale,
    key:"gros_escale",
    expand:"gros.escale",
    checked:true,
    width:150,
    ellipsis: true,
},
{
    title:"Accostage",
    dataIndex:"gros",
    schema:['gros', 'accostage'],
    render: (record:any) => record?.accostage,
    key:"gros_accostage",
    expand:"gros.accostage",
    checked:true,
    width:150,
    ellipsis: true,
},
{
    title:"Raison sociale",
    dataIndex:"gros",
    schema:['gros', 'port_emission', 'raison_sociale'],
    render: (record:any) => record?.port_emission?.raison_sociale,
    key:"gros_port_emission_raison_sociale",
    expand:"gros.port_emission.raison_sociale",
    checked:true,
    width:150,
    ellipsis: true,
},
{
    title:"Code",
    dataIndex:"gros",
    schema:['gros', 'port_emission', 'code'],
    render: (record:any) => record?.port_emission?.code,
    key:"gros_port_emission_code",
    expand:"gros.port_emission.code",
    checked:true,
    width:150,
    ellipsis: true,
},
{
    title:"Code",
    dataIndex:"gros",
    schema:['gros', 'port_emission', 'pays', 'code'],
    render: (record:any) => record?.port_emission?.pays?.code,
    key:"gros_port_emission_pays_code",
    expand:"gros.port_emission.pays.code",
    checked:true,
    width:150,
    ellipsis: true,
},
{
    title:"Alpha2",
    dataIndex:"gros",
    schema:['gros', 'port_emission', 'pays', 'alpha2'],
    render: (record:any) => record?.port_emission?.pays?.alpha2,
    key:"gros_port_emission_pays_alpha2",
    expand:"gros.port_emission.pays.alpha2",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Alpha3",
    dataIndex:"gros",
    schema:['gros', 'port_emission', 'pays', 'alpha3'],
    render: (record:any) => record?.port_emission?.pays?.alpha3,
    key:"gros_port_emission_pays_alpha3",
    expand:"gros.port_emission.pays.alpha3",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Nom fr fr",
    dataIndex:"gros",
    schema:['gros', 'port_emission', 'pays', 'nom_fr_fr'],
    render: (record:any) => record?.port_emission?.pays?.nom_fr_fr,
    key:"gros_port_emission_pays_nom_fr_fr",
    expand:"gros.port_emission.pays.nom_fr_fr",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Nom en gb",
    dataIndex:"gros",
    schema:['gros', 'port_emission', 'pays', 'nom_en_gb'],
    render: (record:any) => record?.port_emission?.pays?.nom_en_gb,
    key:"gros_port_emission_pays_nom_en_gb",
    expand:"gros.port_emission.pays.nom_en_gb",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Nom",
    dataIndex:"gros",
    schema:['gros', 'navire', 'nom'],
    render: (record:any) => record?.navire?.nom,
    key:"gros_navire_nom",
    expand:"gros.navire.nom",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Code",
    dataIndex:"gros",
    schema:['gros', 'navire', 'code'],
    render: (record:any) => record?.navire?.code,
    key:"gros_navire_code",
    expand:"gros.navire.code",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Raison sociale",
    dataIndex:"gros",
    schema:['gros', 'armateur', 'raison_sociale'],
    render: (record:any) => record?.armateur?.raison_sociale,
    key:"gros_armateur_raison_sociale",
    expand:"gros.armateur.raison_sociale",
    checked:true,
    width:150,
    ellipsis: true,
},
{
    title:"Code",
    dataIndex:"gros",
    schema:['gros', 'armateur', 'code'],
    render: (record:any) => record?.armateur?.code,
    key:"gros_armateur_code",
    expand:"gros.armateur.code",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Raison sociale",
    dataIndex:"gros",
    schema:['gros', 'consignataire', 'raison_sociale'],
    render: (record:any) => record?.consignataire?.raison_sociale,
    key:"gros_consignataire_raison_sociale",
    expand:"gros.consignataire.raison_sociale",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Code",
    dataIndex:"gros",
    schema:['gros', 'consignataire', 'code'],
    render: (record:any) => record?.consignataire?.code,
    key:"gros_consignataire_code",
    expand:"gros.consignataire.code",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Designation",
    dataIndex:"gros",
    schema:['gros', 'bareme', 'designation'],
    render: (record:any) => record?.bareme?.designation,
    key:"gros_bareme_designation",
    expand:"gros.bareme.designation",
    checked:true,
    width:150,
    ellipsis: true,
},
{
    title:"Starting date",
    dataIndex:"gros",
    schema:['gros', 'bareme', 'starting_date'],
    render: (record:any) => record?.bareme?.starting_date,
    key:"gros_bareme_starting_date",
    expand:"gros.bareme.starting_date",
    checked:true,
    width:150,
    ellipsis: true,
},
{
    title:"Ending date",
    dataIndex:"gros",
    schema:['gros', 'bareme', 'ending_date'],
    render: (record:any) => record?.bareme?.ending_date,
    key:"gros_bareme_ending_date",
    expand:"gros.bareme.ending_date",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"� partir de la date d'accostage",
    dataIndex:"gros",
    schema:['gros', 'bareme', 'accostage'],
    render: (record:any) => record?.bareme?.accostage,
    key:"gros_bareme_accostage",
    expand:"gros.bareme.accostage",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Regime d�signation",
    dataIndex:"gros",
    schema:['gros', 'regime', 'designation'],
    render: (record:any) => record?.regime?.designation,
    key:"gros_regime_designation",
    expand:"gros.regime.designation",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Methode calcule",
    dataIndex:"gros",
    schema:['gros', 'regime', 'methode_calcule'],
    render: (record:any) => record?.regime?.methode_calcule,
    key:"gros_regime_methode_calcule",
    expand:"gros.regime.methode_calcule",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Regime enterposage",
    dataIndex:"gros",
    schema:['gros', 'regime', 'enterposage'],
    render: (record:any) => record?.regime?.enterposage,
    key:"gros_regime_enterposage",
    expand:"gros.regime.enterposage",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Regime color",
    dataIndex:"gros",
    schema:['gros', 'regime', 'color'],
    render: (record:any) => record?.regime?.color,
    key:"gros_regime_color",
    expand:"gros.regime.color",
    checked:true,
    width:150,
    ellipsis: true,
},
{
    title:"Designation",
    dataIndex:"gros",
    schema:['gros', 'regime', 'parc', 'designation'],
    render: (record:any) => record?.regime?.parc?.designation,
    key:"gros_regime_parc_designation",
    expand:"gros.regime.parc.designation",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Numero",
    dataIndex:"numero",
    schema:['numero'],
    key:"numero",
    render: (record:any) => record,
    checked:true,
    width:150,
    ellipsis: true,
},
{
    title:"Groupage",
    dataIndex:"groupage",
    schema:['groupage'],
    key:"groupage",
    render: (record:any) => record,
    checked:true,
    width:150,
    ellipsis: true,
},
{
    title:"Date depotage",
    dataIndex:"date_depotage",
    schema:['date_depotage'],
    key:"date_depotage",
    render: (record:any) => record,
    checked:true,
    width:150,
    ellipsis: true,
},
{
    title:"Depote",
    dataIndex:"depote",
    schema:['depote'],
    key:"depote",
    render: (record:any) => record,
    checked:true,
    width:150,
    ellipsis: true,
},
{
    title:"Observation depotage",
    dataIndex:"observation_depotage",
    schema:['observation_depotage'],
    key:"observation_depotage",
    render: (record:any) => record,
    checked:true,
    width:150,
    ellipsis: true,
},
{
    title:"Bl",
    dataIndex:"bl",
    schema:['bl'],
    key:"bl",
    render: (record:any) => record,
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Designation",
    dataIndex:"designation",
    schema:['designation'],
    key:"designation",
    render: (record:any) => record,
    checked:true,
    width:150,
    ellipsis: true,
},
{
    title:"Raison sociale",
    dataIndex:"client",
    schema:['client', 'raison_sociale'],
    render: (record:any) => record?.raison_sociale,
    key:"client_raison_sociale",
    expand:"client.raison_sociale",
    checked:true,
    width:150,
    ellipsis: true,
},
{
    title:"Adress",
    dataIndex:"client",
    schema:['client', 'adress'],
    render: (record:any) => record?.adress,
    key:"client_adress",
    expand:"client.adress",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Email",
    dataIndex:"client",
    schema:['client', 'email'],
    render: (record:any) => record?.email,
    key:"client_email",
    expand:"client.email",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Tel",
    dataIndex:"client",
    schema:['client', 'tel'],
    render: (record:any) => record?.tel,
    key:"client_tel",
    expand:"client.tel",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Code",
    dataIndex:"client",
    schema:['client', 'code'],
    render: (record:any) => record?.code,
    key:"client_code",
    expand:"client.code",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Rc",
    dataIndex:"client",
    schema:['client', 'RC'],
    render: (record:any) => record?.RC,
    key:"client_RC",
    expand:"client.RC",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Nif",
    dataIndex:"client",
    schema:['client', 'NIF'],
    render: (record:any) => record?.NIF,
    key:"client_NIF",
    expand:"client.NIF",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Ai",
    dataIndex:"client",
    schema:['client', 'AI'],
    render: (record:any) => record?.AI,
    key:"client_AI",
    expand:"client.AI",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Nis",
    dataIndex:"client",
    schema:['client', 'NIS'],
    render: (record:any) => record?.NIS,
    key:"client_NIS",
    expand:"client.NIS",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Soumis tva",
    dataIndex:"client",
    schema:['client', 'soumis_tva'],
    render: (record:any) => record?.soumis_tva,
    key:"client_soumis_tva",
    expand:"client.soumis_tva",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Raison sociale",
    dataIndex:"transitaire",
    schema:['transitaire', 'raison_sociale'],
    render: (record:any) => record?.raison_sociale,
    key:"transitaire_raison_sociale",
    expand:"transitaire.raison_sociale",
    checked:true,
    width:150,
    ellipsis: true,
},
{
    title:"Adress",
    dataIndex:"transitaire",
    schema:['transitaire', 'adress'],
    render: (record:any) => record?.adress,
    key:"transitaire_adress",
    expand:"transitaire.adress",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Email",
    dataIndex:"transitaire",
    schema:['transitaire', 'email'],
    render: (record:any) => record?.email,
    key:"transitaire_email",
    expand:"transitaire.email",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Tel",
    dataIndex:"transitaire",
    schema:['transitaire', 'tel'],
    render: (record:any) => record?.tel,
    key:"transitaire_tel",
    expand:"transitaire.tel",
    checked:false,
    width:150,
    ellipsis: true,
},
{
    title:"Soumis tva",
    dataIndex:"transitaire",
    schema:['transitaire', 'soumis_tva'],
    render: (record:any) => record?.soumis_tva,
    key:"transitaire_soumis_tva",
    expand:"transitaire.soumis_tva",
    checked:false,
    width:150,
    ellipsis: true,
},
];