# Generated by Django 3.2 on 2022-01-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturelibre',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturelibre',
            name='ref',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='V/Réf'),
        ),
        migrations.AddField(
            model_name='facturelibre',
            name='type_dossier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalfacturelibre',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfacturelibre',
            name='ref',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='V/Réf'),
        ),
        migrations.AddField(
            model_name='historicalfacturelibre',
            name='type_dossier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
