# Generated by Django 3.2 on 2022-01-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20220118_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturelibre',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfacturelibre',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
