# Generated by Django 3.2 on 2022-01-18 14:35

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20220118_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturelibre',
            name='numero',
            field=models.CharField(default=billing.models.getNumeroFactureLibre, max_length=15, verbose_name='numéro de facture'),
        ),
        migrations.AlterField(
            model_name='historicalfacturelibre',
            name='numero',
            field=models.CharField(default=billing.models.getNumeroFactureLibre, max_length=15, verbose_name='numéro de facture'),
        ),
    ]
