# Generated by Django 3.2 on 2022-02-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20220125_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-id'], 'verbose_name_plural': 'factures'},
        ),
        migrations.AlterModelOptions(
            name='proforma',
            options={'ordering': ['-id'], 'verbose_name_plural': 'proformas'},
        ),
    ]
