# Generated by Django 3.2 on 2022-02-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20220209_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factureavoire',
            name='timber',
        ),
        migrations.RemoveField(
            model_name='historicalfactureavoire',
            name='timber',
        ),
    ]
