# Generated by Django 4.0.3 on 2022-04-13 11:12

import billing.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_sousarticle_invoiced'),
        ('billing', '0010_facturegroupage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturegroupage',
            options={'ordering': ['-id'], 'verbose_name_plural': 'factures groupage'},
        ),
        migrations.CreateModel(
            name='ProformaGroupage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=billing.models.getNumeroProformaGroupage, max_length=9)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('HT', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('TVA', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('TTC', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_debeur', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('TR', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('timber', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('valide', models.BooleanField(blank=True, default=False, null=True)),
                ('trashed', models.BooleanField(blank=True, default=False, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.article')),
                ('gros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gros')),
                ('sous_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sousarticle')),
            ],
            options={
                'verbose_name_plural': 'proformas groupage',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LignePrestationGroupage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubrique', models.CharField(max_length=100)),
                ('debeur', models.BooleanField(default=False)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('tarif', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('HT', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('TVA', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('TTC', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.proformagroupage')),
            ],
            options={
                'verbose_name_plural': 'lignes prestation',
            },
        ),
        migrations.AddField(
            model_name='facturegroupage',
            name='Proforma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.proformagroupage'),
        ),
    ]
