# Generated by Django 4.0.3 on 2022-04-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_remove_facturegroupage_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturegroupage',
            old_name='Proforma',
            new_name='proforma',
        ),
    ]
