# Generated by Django 4.0.3 on 2022-04-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_rename_proforma_facturegroupage_proforma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformagroupage',
            name='timber',
        ),
    ]
