# Generated by Django 4.0.3 on 2022-04-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_remove_proformagroupage_timber'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformagroupage',
            name='REMISE',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='proformagroupage',
            name='remise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proformagroupage',
            name='tva',
            field=models.BooleanField(default=True, verbose_name='TVA'),
        ),
    ]
