# Generated by Django 4.0.3 on 2022-04-13 13:11

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_proformagroupage_remise_proformagroupage_remise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturegroupage',
            name='numero',
            field=models.CharField(default=billing.models.getNumeroFactureGroupage, max_length=12),
        ),
        migrations.AlterField(
            model_name='proformagroupage',
            name='numero',
            field=models.CharField(default=billing.models.getNumeroProformaGroupage, max_length=12),
        ),
    ]
