# Generated by Django 4.0.3 on 2022-04-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_facturegroupage_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformagroupage',
            name='date_proforma',
            field=models.DateField(null=True),
        ),
    ]
