# Generated by Django 4.0.3 on 2022-04-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_rename_total_debeur_proformagroupage_debeur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligneprestationgroupage',
            name='debeur',
        ),
    ]
