# Generated by Django 4.0.3 on 2022-04-14 11:45

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_facturegroupage_debeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(default=billing.models.getNumeroFacture, max_length=9),
        ),
        migrations.AlterField(
            model_name='historicalfacture',
            name='numero',
            field=models.CharField(default=billing.models.getNumeroFacture, max_length=9),
        ),
    ]
