# Generated by Django 4.0.3 on 2022-04-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_alter_facture_numero_alter_historicalfacture_numero'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LignePrestationGroupage',
            new_name='LigneFactureGroupage',
        ),
    ]
