# Generated by Django 4.0.3 on 2022-04-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_rename_ligneprestationgroupage_lignefacturegroupage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LigneFactureGroupage',
            new_name='LigneProformaGroupage',
        ),
    ]
