# Generated by Django 4.0.3 on 2022-04-17 13:51

import billing.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_sousarticle_invoiced'),
        ('billing', '0025_paiementgroupage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBonSortieGroupage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero', models.CharField(default=billing.models.getNumeroBonSortieGroupage, max_length=50)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateField(blank=True, editable=False)),
                ('d10', models.CharField(max_length=50)),
                ('badge', models.CharField(max_length=50)),
                ('matricule', models.CharField(max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('facture', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.facturegroupage')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sous_article', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.sousarticle')),
            ],
            options={
                'verbose_name': 'historical bon sortie groupage',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BonSortieGroupage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=billing.models.getNumeroBonSortieGroupage, max_length=50)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('d10', models.CharField(max_length=50)),
                ('badge', models.CharField(max_length=50)),
                ('matricule', models.CharField(max_length=50)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.facturegroupage')),
                ('sous_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sousarticle')),
            ],
            options={
                'verbose_name_plural': 'bons de sortie groupage',
            },
        ),
    ]
