# Generated by Django 4.0.3 on 2022-04-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_historicalbonsortiegroupage_bonsortiegroupage'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='DEBEUR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalfacture',
            name='DEBEUR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalproforma',
            name='DEBEUR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalproforma',
            name='debeur',
            field=models.BooleanField(default=False, verbose_name='DEBEUR'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='DEBEUR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='proforma',
            name='debeur',
            field=models.BooleanField(default=False, verbose_name='DEBEUR'),
        ),
    ]
