# Generated by Django 3.2.16 on 2022-10-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_facture_debeur_historicalfacture_debeur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalbonsortie',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical bon sortie', 'verbose_name_plural': 'historical bons de sortie'},
        ),
        migrations.AlterModelOptions(
            name='historicalbonsortiegroupage',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical bon sortie groupage', 'verbose_name_plural': 'historical bons de sortie groupage'},
        ),
        migrations.AlterModelOptions(
            name='historicalfacture',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical facture', 'verbose_name_plural': 'historical factures'},
        ),
        migrations.AlterModelOptions(
            name='historicalfactureavoire',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical facture avoire', 'verbose_name_plural': 'historical factures avoire'},
        ),
        migrations.AlterModelOptions(
            name='historicalfacturecomplementaire',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical facture complementaire', 'verbose_name_plural': 'historical factures complimentaire'},
        ),
        migrations.AlterModelOptions(
            name='historicalfacturelibre',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical facture libre', 'verbose_name_plural': 'historical factures libre'},
        ),
        migrations.AlterModelOptions(
            name='historicalproforma',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical proforma', 'verbose_name_plural': 'historical proformas'},
        ),
        migrations.AlterField(
            model_name='historicalbonsortie',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalbonsortiegroupage',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfacture',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfactureavoire',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfacturecomplementaire',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfacturelibre',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalproforma',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
