# Generated by Django 4.2.5 on 2023-10-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bareme', '0025_historicalrubrique_direction_rubrique_direction_and_more'),
        ('billing', '0029_ligneprestation_code_comptable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='rubrique_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rubrique_commande', to='bareme.rubrique'),
        ),
        migrations.AddField(
            model_name='ligneprestationarticle',
            name='rubrique_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rubrique_prestation_article', to='bareme.rubrique'),
        ),
    ]
