# Generated by Django 4.2.5 on 2023-10-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_ligneprestationarticle_code_comptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproforma',
            name='entreposage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='proforma',
            name='entreposage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
