# Generated by Django 4.2.5 on 2023-10-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_historicalproforma_entreposage_proforma_entreposage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproforma',
            name='entreposage',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='entreposage',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
