# Generated by Django 4.0.3 on 2022-03-31 14:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import groupage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0014_remove_sousarticle_date_depotage_and_more'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremeGroupage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RubriqueGroupage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VisiteGroupage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visite', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('numero', models.CharField(default=groupage.models.getNumeroVisiteGroupage, max_length=9)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_visite', models.DateField(default=datetime.datetime.now)),
                ('type_visite', models.CharField(choices=[('Visite douane', 'Visite douane'), ('Visite D41', 'Visite D41')], max_length=15)),
                ('badge', models.CharField(max_length=50)),
                ('test', models.CharField(blank=True, max_length=50, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.article')),
                ('gros', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.gros')),
                ('sous_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sousarticle')),
                ('transitaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.transitaire')),
            ],
            options={
                'verbose_name_plural': 'visites groupage',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='SejourGroupage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dangereux', models.BooleanField(default=False)),
                ('jour_min', models.IntegerField(blank=True)),
                ('jour_max', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('bareme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groupage.baremegroupage')),
            ],
            options={
                'verbose_name_plural': 'séjours',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PrestationGroupage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dangereux', models.BooleanField(blank=True, default=False, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=19)),
                ('bareme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupage.baremegroupage', verbose_name='Bareme groupage')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupage.rubriquegroupage', verbose_name='Rubrique groupage')),
            ],
        ),
        migrations.CreateModel(
            name='FactureGroupage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=groupage.models.getNumeroFacture, max_length=9)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('HT', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('TVA', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('TTC', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('TR', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('timber', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('a_terme', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.article')),
                ('gros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gros')),
                ('sous_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sousarticle')),
            ],
            options={
                'verbose_name_plural': 'factures groupage',
                'ordering': ['-id'],
            },
        ),
    ]
