# Generated by Django 4.0.3 on 2022-04-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubriquegroupage',
            name='type',
            field=models.CharField(choices=[('visite', 'visite'), ('automatique', 'Automatique'), ('occasionelle', 'Occasionelle')], default=2, max_length=50),
        ),
    ]
