# Generated by Django 4.0.3 on 2022-04-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupage', '0002_rubriquegroupage_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baremegroupage',
            options={'ordering': ['id'], 'verbose_name_plural': 'baremes'},
        ),
        migrations.AlterModelOptions(
            name='facturegroupage',
            options={'ordering': ['-id'], 'verbose_name_plural': 'factures'},
        ),
        migrations.AlterModelOptions(
            name='prestationgroupage',
            options={'ordering': ['id'], 'verbose_name_plural': 'prestations'},
        ),
        migrations.AlterModelOptions(
            name='rubriquegroupage',
            options={'ordering': ['id'], 'verbose_name_plural': 'rubriques'},
        ),
        migrations.AlterModelOptions(
            name='visitegroupage',
            options={'ordering': ['id'], 'verbose_name_plural': 'viites'},
        ),
        migrations.RemoveField(
            model_name='visitegroupage',
            name='test',
        ),
    ]
