# Generated by Django 4.0.3 on 2022-04-10 11:37

from django.db import migrations, models
import groupage.models


class Migration(migrations.Migration):

    dependencies = [
        ('groupage', '0003_alter_baremegroupage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitegroupage',
            name='numero',
            field=models.CharField(default=groupage.models.getNumeroVisiteGroupage, max_length=17),
        ),
    ]
