# Generated by Django 4.0.3 on 2022-04-11 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bareme', '0011_alter_historicalrubrique_categorie_and_more'),
        ('groupage', '0004_alter_visitegroupage_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestationgroupage',
            name='bareme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bareme.bareme', verbose_name='Bareme groupage'),
        ),
        migrations.AlterField(
            model_name='prestationgroupage',
            name='rubrique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bareme.rubrique'),
        ),
        migrations.AlterField(
            model_name='sejourgroupage',
            name='bareme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bareme.bareme'),
        ),
        migrations.DeleteModel(
            name='BaremeGroupage',
        ),
        migrations.DeleteModel(
            name='RubriqueGroupage',
        ),
    ]
