# Generated by Django 4.0.3 on 2022-04-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupage', '0005_alter_prestationgroupage_bareme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sejourgroupage',
            name='bareme',
        ),
        migrations.DeleteModel(
            name='PrestationGroupage',
        ),
        migrations.DeleteModel(
            name='SejourGroupage',
        ),
    ]
