# Generated by Django 4.0.3 on 2022-04-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupage', '0006_remove_sejourgroupage_bareme_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FactureGroupage',
        ),
    ]
