# Generated by Django 4.0.4 on 2022-04-27 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_sousarticle_transitaire'),
        ('reference', '0003_box_parc'),
        ('groupage', '0007_delete_facturegroupage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionGroupgae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.box')),
                ('sous_Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sousarticle')),
            ],
        ),
    ]
