# Generated by Django 4.0.4 on 2022-04-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_sousarticle_transitaire'),
        ('reference', '0003_box_parc'),
        ('groupage', '0008_positiongroupgae'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PositionGroupgae',
            new_name='PositionGroupage',
        ),
    ]
