# Generated by Django 4.0.4 on 2022-04-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupage', '0009_rename_positiongroupgae_positiongroupage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positiongroupage',
            old_name='sous_Article',
            new_name='sous_article',
        ),
    ]
