# Generated by Django 3.2 on 2022-01-18 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'agents',
            },
        ),
        migrations.CreateModel(
            name='Armateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'armateurs',
            },
        ),
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200, unique=True)),
                ('adress', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'banques',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200, unique=True)),
                ('adress', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('RC', models.CharField(blank=True, max_length=50, null=True)),
                ('NIF', models.CharField(blank=True, max_length=50, null=True)),
                ('AI', models.CharField(blank=True, max_length=50, null=True)),
                ('NIS', models.CharField(blank=True, max_length=50, null=True)),
                ('soumis_tva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'clients',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Consignataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'consignataires',
            },
        ),
        migrations.CreateModel(
            name='Groupeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200, unique=True)),
                ('adress', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('soumis_tva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'groupeurs',
            },
        ),
        migrations.CreateModel(
            name='Navire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'navires',
            },
        ),
        migrations.CreateModel(
            name='Parc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'parcs',
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('alpha2', models.CharField(max_length=2)),
                ('alpha3', models.CharField(max_length=3)),
                ('nom_fr_fr', models.CharField(max_length=50, unique=True)),
                ('nom_en_gb', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'pays',
            },
        ),
        migrations.CreateModel(
            name='Transitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200, unique=True)),
                ('adress', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('soumis_tva', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'types',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, max_length=200, null=True)),
                ('lignes', models.IntegerField(blank=True, null=True)),
                ('ranges', models.IntegerField(blank=True, null=True)),
                ('gerbage', models.IntegerField(blank=True, default=5, null=True)),
                ('parc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.parc')),
            ],
            options={
                'verbose_name_plural': 'zones',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('pays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.pays')),
            ],
            options={
                'verbose_name_plural': 'ports',
            },
        ),
    ]
