# Generated by Django 4.0.4 on 2022-04-25 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='parc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.parc'),
        ),
    ]
