# Generated by Django 4.2.2 on 2023-09-11 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bareme', '0021_prestationoccasionnellegroupage_and_more'),
        ('reference', '0003_box_parc'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bareme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bareme.bareme'),
        ),
    ]
