# Generated by Django 4.2.5 on 2023-10-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_client_bareme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('couleur', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'verbose_name_plural': 'directions',
            },
        ),
    ]
