# Generated by Django 4.2.5 on 2023-12-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adress',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='raison_sociale',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
