# Generated by Django 3.2 on 2022-01-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalGros',
        ),
    ]
