# Generated by Django 3.2 on 2022-01-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_historicalgros'),
    ]

    operations = [
        migrations.AddField(
            model_name='gros',
            name='D15',
            field=models.BooleanField(default=False),
        ),
    ]
