# Generated by Django 3.2 on 2022-01-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_gros_d15'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalSousArticle',
        ),
    ]
