# Generated by Django 3.2 on 2022-01-18 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
        ('app', '0005_delete_historicalsousarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sousarticle',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.client'),
        ),
        migrations.AddField(
            model_name='sousarticle',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
