# Generated by Django 3.2 on 2022-02-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220202_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gros',
            name='D15',
        ),
        migrations.RemoveField(
            model_name='gros',
            name='OT',
        ),
    ]
