# Generated by Django 3.2 on 2022-02-02 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bareme', '0003_regime_enterposage'),
        ('app', '0008_auto_20220202_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gros',
            name='regeme',
        ),
        migrations.AddField(
            model_name='gros',
            name='regime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bareme.regime', verbose_name='Régime'),
        ),
    ]
