# Generated by Django 3.2 on 2022-02-07 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bareme', '0004_alter_regime_designation'),
        ('reference', '0001_initial'),
        ('app', '0009_auto_20220202_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gros',
            name='regime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bareme.regime', verbose_name='Régime'),
        ),
        migrations.AlterField(
            model_name='tc',
            name='type_tc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.type'),
        ),
    ]
