# Generated by Django 3.2 on 2022-02-16 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bareme', '0006_alter_regime_color'),
        ('app', '0010_auto_20220207_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gros',
            name='regime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bareme.regime', verbose_name='Régime'),
        ),
    ]
