# Generated by Django 3.2 on 2022-03-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_gros_regime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gros',
            name='gros',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gros',
            name='numero',
            field=models.CharField(max_length=50),
        ),
    ]
