# Generated by Django 3.2 on 2022-03-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bareme', '0007_alter_regime_color'),
        ('app', '0012_auto_20220303_1215'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gros',
            unique_together={('numero', 'accostage', 'regime')},
        ),
    ]
