# Generated by Django 4.0.3 on 2022-03-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_gros_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sousarticle',
            name='date_depotage',
        ),
        migrations.AddField(
            model_name='article',
            name='date_depotage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='depote',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='observation_depotage',
            field=models.CharField(blank=True, default='R.A.S', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='date_depotage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='depote',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='observation_depotage',
            field=models.CharField(blank=True, default='R.A.S', max_length=400, null=True),
        ),
    ]
