# Generated by Django 4.0.3 on 2022-04-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_sousarticle_date_depotage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sousarticle',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
