# Generated by Django 4.0.3 on 2022-04-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_sousarticle_invoiced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sousarticle',
            name='invoiced',
        ),
    ]
