# Generated by Django 4.0.4 on 2022-04-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_sousarticle_invoiced'),
    ]

    operations = [
        migrations.AddField(
            model_name='sousarticle',
            name='dangereux',
            field=models.BooleanField(default=False),
        ),
    ]
