# Generated by Django 4.0.4 on 2022-04-26 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_box_parc'),
        ('app', '0018_sousarticle_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='sousarticle',
            name='transitaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.transitaire'),
        ),
    ]
