# Generated by Django 4.0.4 on 2022-04-27 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupage', '0010_rename_sous_article_positiongroupage_sous_article'),
        ('app', '0019_sousarticle_transitaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sousarticle',
            name='box',
        ),
        migrations.AddField(
            model_name='sousarticle',
            name='postition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groupage.positiongroupage'),
        ),
    ]
