# Generated by Django 3.2.16 on 2022-10-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_sousarticle_postition_sousarticle_box'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalarticle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical article', 'verbose_name_plural': 'historical articles'},
        ),
        migrations.AlterModelOptions(
            name='historicalbulletinsescort',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical bulletins escort', 'verbose_name_plural': "historical bulletins d'escort"},
        ),
        migrations.AlterModelOptions(
            name='historicalposition',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical position', 'verbose_name_plural': 'historical positions'},
        ),
        migrations.AlterModelOptions(
            name='historicalscelle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical scelle', 'verbose_name_plural': 'historical scelles'},
        ),
        migrations.AlterModelOptions(
            name='historicalvisite',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical visite', 'verbose_name_plural': 'historical visites'},
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalbulletinsescort',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalposition',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalscelle',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalvisite',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
