# Generated by Django 3.2.16 on 2022-10-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_tc_billed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc',
            name='billed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
