# Generated by Django 3.2.16 on 2022-10-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_tc_billed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sousarticle',
            name='bl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
