# Generated by Django 4.2.2 on 2023-09-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_sousarticle_bl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sousarticle',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
