# Generated by Django 4.2.2 on 2023-09-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_sousarticle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sousarticle',
            name='designation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
