# Generated by Django 4.2.5 on 2023-12-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_sousarticle_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sousarticle',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
